### ISSUE TITLE
ROI API 

### ISSUE THREAD

**Issue by Poseyy** [thegismar/yearn_roi#1]
Hi there. Is it possible to hit the endpoint in your readme? Getting good status but no data. 

```
resp = requests.get('https://py-earn.herokuapp.com/api')
resp = resp.json()

roi = resp['crv']
```

**Comment by thegismar** [comment]
Hi!

I'm so sorry, I stopped maintaining this since I started working on a subgraph to provide a better and more reliable form to query this and lots of more data from yearn. There's one API out there by x48 that uses the same calculations.

**Comment by Poseyy** [comment]
Right on, thanks for the quick reply!
