### ISSUE TITLE
Endpoint not working

### ISSUE THREAD

**Issue by hpiyankov** [thegismar/yearn_roi#2]
The endpoint for the data seems to be invalid (e.g. when I try to execute the code in colab I get no response). Maybe the endpoint has changed?

**Comment by thegismar** [comment]
yes, i'm not maintaining this anymore, there's a way better api here that uses the same formulas:

https://github.com/x48-crypto/yearn-apy-lambda

i'll either delete this or put a warning in the readme, sorry
